// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadSecurity.Backend.Data;

#nullable disable

namespace SquadSecurity.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240821040857_addEntidadesv2")]
    partial class addEntidadesv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Excepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FechaAtencion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabiliutadoresRelacionados")
                        .HasColumnType("int");

                    b.Property<string>("Sustento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Excepciones");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Habilitador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int>("CodigoAmbienteCapturaE")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCriterio")
                        .HasColumnType("int");

                    b.Property<int>("CodigoDimension")
                        .HasColumnType("int");

                    b.Property<int>("CodigoDominio")
                        .HasColumnType("int");

                    b.Property<int>("CodigoEstadoCumplimiento")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoEtapaCaptura")
                        .HasColumnType("int");

                    b.Property<int>("CodigoImprescindible")
                        .HasColumnType("int");

                    b.Property<int>("CodigoLineamiento")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPlanAccion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CodigoResponsable")
                        .HasColumnType("int");

                    b.Property<int>("CodigoTipoSolucion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdExcepcion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Titulo")
                        .IsUnique();

                    b.ToTable("Habilitadores");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Iniciativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aplicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("Negocio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Iniciativas");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EstadoAuditoria")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioAuditoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Valor", "Abreviatura")
                        .IsUnique();

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.RevisionCab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoAnalista")
                        .HasColumnType("int");

                    b.Property<int>("CodigoArquitecto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoIniciativa")
                        .HasColumnType("int");

                    b.Property<int>("CodigoQuarter")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSquad")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIniciativa", "CodigoSquad")
                        .IsUnique();

                    b.ToTable("RevisionCabs");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.RevisionDet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCabecera")
                        .HasColumnType("int");

                    b.Property<int>("CodigoEstadoCumplimiento")
                        .HasColumnType("int");

                    b.Property<int>("CodigoExcepcion")
                        .HasColumnType("int");

                    b.Property<int>("CodigoHabilitador")
                        .HasColumnType("int");

                    b.Property<int>("CodigoIniciativa")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSquad")
                        .HasColumnType("int");

                    b.Property<int?>("Comentario")
                        .HasColumnType("int");

                    b.Property<string>("Entregable")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<int>("RevisionCabId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RevisionCabId")
                        .IsUnique();

                    b.ToTable("RevisionDets");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoAnalista")
                        .HasColumnType("int");

                    b.Property<int>("CodigoArquitecto")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("Negocio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tribu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.SquadDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("CodigoIntegrante")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSquad")
                        .HasColumnType("int");

                    b.Property<int?>("Comentario")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAuditoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaAuditoria")
                        .HasColumnType("datetime2");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAuditoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SquadId")
                        .IsUnique();

                    b.ToTable("SquadDetalles");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.RevisionDet", b =>
                {
                    b.HasOne("SquadSecurity.Shared.Entities.RevisionCab", "RevisionCab")
                        .WithMany("RevisionDets")
                        .HasForeignKey("RevisionCabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RevisionCab");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.SquadDetalle", b =>
                {
                    b.HasOne("SquadSecurity.Shared.Entities.Squad", "Squad")
                        .WithMany("SquadDets")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.RevisionCab", b =>
                {
                    b.Navigation("RevisionDets");
                });

            modelBuilder.Entity("SquadSecurity.Shared.Entities.Squad", b =>
                {
                    b.Navigation("SquadDets");
                });
#pragma warning restore 612, 618
        }
    }
}
